CREATE TABLE IF NOT EXISTS UserStats (
    id BIGINT UNIQUE PRIMARY KEY NOT NULL,
    firstReq TIMESTAMP DEFAULT NOW() NOT NULL,
    amount INT DEFAULT 0 NOT NULL,
    lastPair VARCHAR(255) DEFAULT 'Неизвестно' NOT NULL
);